version: '2'

services:

  ### Applications Code Container
  applications:
    image: tianon/true
    volumes:
      - ${APPLICATION}:/var/www

### Networks Setup
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
