    neo4j:
        ports:
            - '7401:7474'
            - '7602:7687'
        environment:
            - NEO4J_AUTH=none
        volumes:
            - '/root/neo4j/data:/data'
            - '/root/neo4j/logs:/logs'
        image: 'neo4j:latest'
