blank_issues_enabled: false
contact_links:
  - name: Support question
    url: https://gitter.im/LaraDock/laradock
    about: 'This repository is only for reporting bugs. If you need help, get in touch with us via Gitter.'
