baseurl = "http://laradock.io/"
languageCode = "en-us"
publishDir = "../"
title = "Laradock Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Mahmoud Zalt"
	description = "Laradock documentations."
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/laradock/laradock"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "laradock"
	email   = ""

# ------- MENU START -----------------------------------------

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Documentation"
	url    = "documentation/"
	weight = 20

[[menu.main]]
	name   = "Related Projects"
	url    = "related-projects/"
	weight = 30

[[menu.main]]
	name   = "Help & Questions"
	url    = "help/"
	weight = 40

[[menu.main]]
	name   = "Contributing"
	url    = "contributing/"
	weight = 50

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 60

# ------- MENU END -----------------------------------------

[blackfriday]
	smartypants	= false
	fractions = false
	smartDashes = false
	plainIDAnchors = false
